"""
Django settings for developer_search project.

Generated by 'django-admin startproject' using Django 3.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os
from decouple import config
import django_heroku

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
production = True

DEBUG = not production
ALLOWED_HOSTS = ['devxplore.herokuapp.com', 'dev-devxplore.herokuapp.com'] if production else []


# Application definition

INSTALLED_APPS = [
    'search.apps.SearchConfig',
    'pwa',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'htmlmin.middleware.HtmlMinifyMiddleware',
    'htmlmin.middleware.MarkRequestMiddleware',
]

ROOT_URLCONF = 'developer_search.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'developer_search.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
]

# HTML minification ON
HTML_MINIFY = True


# Activate Django heroku
django_heroku.settings(locals())

# For forcing HTTPS 

SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
SECURE_SSL_REDIRECT = True


PWA_APP_NAME = 'DevXplore'
PWA_APP_DESCRIPTION = "A search engine for developers"
PWA_APP_BACKGROUND_COLOR = '#ffffff'
PWA_APP_DISPLAY = 'standalone'
PWA_APP_SCOPE = '/'
PWA_APP_ORIENTATION = 'any'
PWA_APP_START_URL = '/'
PWA_APP_STATUS_BAR_COLOR = 'black-translucent'

PWA_APP_ICONS = [
    {
        'src': 'static/icons/android-icon-36x36.png',
        'sizes': '36x36',
    },
    {
        'src': 'static/icons/android-icon-48x48.png',
        'sizes': '48x48',
    },
    {
        'src': 'static/icons/android-icon-72x72.png',
        'sizes': '72x72',
    },
    {
        'src': 'static/icons/android-icon-96x96.png',
        'sizes': '96x96',
    },
    {
        'src': 'static/icons/android-icon-144x144.png',
        'sizes': '144x144',
    },
    {
        'src': 'static/icons/android-icon-192x192.png',
        'sizes': '192x192',
    },
]


PWA_APP_ICONS_APPLE = [
    {
        'src': 'static/icons/apple-icon-57x57.png',
        'sizes': '57x57',
    },
    {
        'src': 'static/icons/apple-icon-60x60.png',
        'sizes': '60x60',
    },
    {
        'src': 'static/icons/apple-icon-72x72.png',
        'sizes': '72x72',
    },
    {
        'src': 'static/icons/apple-icon-76x76.png',
        'sizes': '76x76',
    },
    {
        'src': 'static/icons/apple-icon-114x114.png',
        'sizes': '114x114',
    },
    {
        'src': 'static/icons/apple-icon-120x120.png',
        'sizes': '120x120',
    },
    {
        'src': 'static/icons/apple-icon-144x144.png',
        'sizes': '144x144',
    },
    {
        'src': 'static/icons/apple-icon-152x152.png',
        'sizes': '152x152',
    },
    {
        'src': 'static/icons/apple-icon-180x180.png',
        'sizes': '180x180',
    },
]

PWA_APP_SPLASH_SCREEN = [
    {
        'src': 'static/logo.png',
        'media': '(device-width: 320px) and (device-height: 568px) and (-webkit-device-pixel-ratio: 2)',
    }
]

PWA_SERVICE_WORKER_PATH = os.path.join(BASE_DIR, 'search/templates/search', 'service_worker.js')


PWA_APP_DIR = 'ltr'
PWA_APP_LANG = 'en-US'
PWA_APP_DEBUG_MODE = True
